export const Categories: { search: string; label: string }[] = [
  { search: "mmorpg", label: "MMORPG" },
  { search: "shooter", label: "Tiro" },
  { search: "strategy", label: "Estratégia" },
  { search: "moba", label: "MOBA" },
  { search: "racing", label: "Corrida" },
  { search: "sports", label: "Esportes" },
  { search: "social", label: "Social" },
  { search: "sandbox", label: "Sandbox" },
  { search: "open-world", label: "Mundo Aberto" },
  { search: "survival", label: "Sobrevivência" },
  { search: "pvp", label: "PvP" },
  { search: "pve", label: "PvE" },
  { search: "pixel", label: "Pixelado" },
  { search: "voxel", label: "Voxel" },
  { search: "zombie", label: "Zumbi" },
  { search: "turn-based", label: "Turnos" },
  { search: "first-person", label: "Primeira Pessoa" },
  { search: "third-person", label: "Terceira Pessoa" },
  { search: "top-down", label: "Visão Superior" },
  { search: "tank", label: "Tanque" },
  { search: "space", label: "Espaço" },
  { search: "sailing", label: "Navegação" },
  { search: "side-scroller", label: "Side-Scroller" },
  { search: "superhero", label: "Super-Herói" },
  { search: "permadeath", label: "Morte permanante" },
  { search: "card", label: "Cartas" },
  { search: "battle-royale", label: "Battle Royale" },
  { search: "mmo", label: "MMO" },
  { search: "mmofps", label: "MMOFPS" },
  { search: "mmotps", label: "MMOTPS" },
  { search: "3d", label: "3D" },
  { search: "2d", label: "2D" },
  { search: "anime", label: "Anime" },
  { search: "fantasy", label: "Fantasia" },
  { search: "sci-fi", label: "Ficção Científica" },
  { search: "fighting", label: "Luta" },
  { search: "action-rpg", label: "RPG de Ação" },
  { search: "action", label: "Ação" },
  { search: "military", label: "Militar" },
  { search: "martial-arts", label: "Artes Marciais" },
  { search: "flight", label: "Voo" },
  { search: "low-spec", label: "Baixa Configuração" },
  { search: "tower-defense", label: "Tower Defense" },
  { search: "horror", label: "Terror" },
  { search: "mmorts", label: "MMORTS" },
];
